### ISSUE TITLE
Running eh-bumpversion removes the final newline in package.json

### ISSUE THREAD

**Issue by CruseCtrl** [tdesposito/EH-Versioner#3]
We use [prettier](https://prettier.io/) on our project, and one of the things that it enforces is that all files should end with a newline.

Part of our build script runs `eh-bumpversion patch`, which changes the version in the `package.json` but also removes this final newline character. This means that the next time the build is run, it will fail because it thinks the file hasn't been formatted with prettier.

It seems that the problem stems from `JSON.stringify` not adding a newline at the end of its output:

https://github.com/tdesposito/EH-Versioner/blob/dbd3ada0539b5d7d52a8720f7fbf82bc83327623/src/index.js#L96

Would it be ok if I raised a pull request to add this newline in? I'll just change the line above to something like `JSON.stringify(pkg, null, 2) + '\\n'`

**Comment by tdesposito** [comment]
Yes, please feel free to issue the pull request. I'll try to incorporate it and update the package as quickly as I can.

**Comment by CruseCtrl** [comment]
@tdesposito thanks, I've created the pull request now: https://github.com/tdesposito/EH-Versioner/pull/4
